services:
  yawsdb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
        - "127.0.0.1:5432:5432"
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - yaws_db_data:/var/lib/postgresql/data
      - yaws_db_backups:/backups

volumes:
    yaws_db_data:
    yaws_db_backups:
