run:
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: false
issues:
  exclude-dirs:
    - internal/server/api
linters:
  enable-all: true
  disable:
    - execinquery
    - exportloopref
    - depguard
    - gci
    - gofumpt
    - gomnd
    - ireturn
    - nlreturn
    - nolintlint
    - revive
    - stylecheck
    - varnamelen
    - wrapcheck
    - wsl
