filename: "mock_{{.InterfaceName | snakecase }}.go"
with-expecter: true
packages:
  yaws/internal/store:
    config:
    interfaces:
      Store:
  yaws/internal/transactional:
    config:
    interfaces:
      Transactional:
